dist: trusty
sudo: required

language: c++

matrix:
    include:
        - os: linux
          compiler: gcc
        - os: osx
          compiler: clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

before_script:
    - cmake .

script:
    - cmake --build . && ctest -VV
